### ISSUE TITLE
Webpage has horizontal scroll on mobile/tablet screens

### ISSUE THREAD

**Issue by ericswpark** [purduehackers/webring#41]
Tested on an iPhone 12 mini:

<img width="540" height="1170" alt="Image" src="https://github.com/user-attachments/assets/e7bf391a-b3cf-46ca-8366-6d068933343e" />

**Comment by kdkasad** [comment]
That definitely looks like at least some of the stylesheets aren't loading. Do you have any settings/extensions/network filters that might affect that?

This is what I see on an iPhone 13  on Safari:
![image](https://github.com/user-attachments/assets/72c50b90-c32f-40a7-ba71-6f46eafa8b47)

Note the different link colors, size of the logo image, etc.

**Comment by ericswpark** [comment]
@kdkasad it's showing that way on Safari running on iOS 18.5. I've tried using different networks but the stylesheet is still not loading.

I don't have this issue on Samsung Internet, though the horizontal scroll still remains.

**Comment by kdkasad** [comment]
> [@kdkasad](https://github.com/kdkasad) it's showing that way on Safari running on iOS 18.5. 

Strange. My screenshot is also Safari on iOS 18.5.

Regardless, there is horizontal scroll even when the stylesheet does apply properly, and that was the point of this issue anyways.

This should be fixed by #44. Can you try running that commit and see if you still have horizontal overflow?

**Comment by ericswpark** [comment]
Still have this issue on the latest production deployment. Also, this issue is present on tablets as well:

<img width="2732" height="2048" alt="Image" src="https://github.com/user-attachments/assets/6cbcddd3-a17d-4409-9ec4-dd20095fd905" />

**Comment by ericswpark** [comment]
Can no longer reproduce on latest iOS/WebKit version, tested on a 12 mini with iOS/WebKit 26.6. Closing.
